name: Add Label on Staging to Master Comparison

on:
  pull_request:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest

    steps:
      - name: Add label
        if: ${{ github.base_ref == 'master' && github.head_ref == 'staging' }}
        uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: manual-branch-update
          # add-labels: staging:master
