name: GitHub Release

on:
  push:
    branches:
      - master

jobs:
  create-tag-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 전체 git 히스토리를 가져옵니다

      - name: Generate tag
        id: tag
        run: |
          # 현재 날짜로 태그 생성 (v2025.1.22-1 형식)
          DATE_TAG=$(date +'v%Y.%-m.%-d')
          
          # 같은 날짜의 기존 태그들을 확인
          EXISTING_TAGS=$(git tag -l "${DATE_TAG}-*")
          
          # 같은 날짜의 마지막 태그 번호를 찾아서 1 증가
          if [ -z "$EXISTING_TAGS" ]; then
            NEW_TAG="${DATE_TAG}-1"
          else
            LAST_NUMBER=$(echo "$EXISTING_TAGS" | sed "s/${DATE_TAG}-//" | sort -n | tail -1)
            NEXT_NUMBER=$((LAST_NUMBER + 1))
            NEW_TAG="${DATE_TAG}-${NEXT_NUMBER}"
          fi
          
          echo "new_tag=${NEW_TAG}" >> $GITHUB_OUTPUT

      - name: Create Tag
        run: |
          git tag ${{ steps.tag.outputs.new_tag }}
          git push origin ${{ steps.tag.outputs.new_tag }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.tag.outputs.new_tag }}
          tag_name: ${{ steps.tag.outputs.new_tag }}
          draft: false
          prerelease: false
