name: Add Label to Staging-to-Master Pull Requests

on:
  pull_request:
    types:
      - opened

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
        # Add 'manual-branch-update' label to PRs that merge between the following branches:
        # master -> staging
        # staging -> prod
        # prod -> staging
        # staging -> master
      - if: |
          (env.BASE_REF == 'master' && env.HEAD_REF == 'staging') ||
          (env.BASE_REF == 'staging' && env.HEAD_REF == 'prod') ||
          (env.BASE_REF == 'prod' && env.HEAD_REF == 'staging') ||
          (env.BASE_REF == 'staging' && env.HEAD_REF == 'master')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['manual-branch-update']
            })
        env:
          BASE_REF: ${{ github.base_ref }}
          HEAD_REF: ${{ github.head_ref }}
