name: Add Label to Staging-to-Master Pull Requests

on:
  pull_request:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest

    steps:
      - name: Add label
        if: ${{ github.base_ref == 'master' && github.head_ref == 'staging' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["manual-branch-update"]
            })
